name: build

on:
  push:
    tags:
        - version*
    branches: 
        - dev
        - master        
  pull_request:
    branches:
        - dev
        - master  

env:
    CICD_REPO_SLUG: jindrapetrik/jpexs-decompiler
    CICD_REFTYPE: ${{ github.ref_type }}
    CICD_REFNAME: ${{ github.ref_name }}
    CICD_COMMIT: ${{ github.sha }}
    CICD_NAME: GitHub Actions
    CICD_EMAIL: GitHub
    CICD_EVENTNAME: ${{ github.event_name }}
    NIGHTLY_BRANCH: dev
    GITHUB_USER: jindrapetrik
    GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest
    container: debian:sid

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDKs
      uses: actions/setup-java@v4
      with:
        distribution: adopt
        architecture: x64
        java-version: |
          8
          21
    - name: Set up PHP
      run: |
        apt update -y -qq
        apt install -y -qq php
    - name: Set up NSis
      run: |
        apt-get -y update
        apt-get -y install nsis
        makensis -VERSION
    - name: Set up ant
      run: |
        apt install -y -qq ant 
    - name: Build
      run: |        
        export CICD_TEMP=${{ runner.temp }}
        chmod a+x ./cicd_scripts/*.sh
        ./cicd_scripts/before_install.sh
        ./cicd_scripts/script.sh
